[CmdletBinding()]
param(
    [Parameter()]
    [string] $RendererPath,
    [Parameter()]
    [string] $InputRoot,
    [Parameter()]
    [string] $OutputRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if ([string]::IsNullOrWhiteSpace($RendererPath)) {
    $RendererPath = Join-Path $root '.tools\resvg\0.47.0\resvg.exe'
}
if ([string]::IsNullOrWhiteSpace($InputRoot)) {
    $InputRoot = Join-Path $root 'assets\native-icons\states\mask'
}
if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
    $OutputRoot = Join-Path $root 'assets\native-icons\raster'
}

# The output is consumed as embedded resources, not generated by an ordinary build.
# For each raster file at raster\<pixel-size>\<name>.png, the UI project should use:
#   LogicalName="OAuthProbe.NativeIcons.<pixel-size>.<name>.png"
# NativeIconCache derives that name and never parses SVG at runtime.
$rendererVersion = '0.47.0'
$rendererLicense = 'MIT (or Apache-2.0), from the tagged resvg 0.47.0 release'
$maxSvgBytes = 16KB
$svgNamespace = 'http://www.w3.org/2000/svg'
$allowedElements = @('svg', 'title', 'g', 'path', 'rect', 'circle')
$allowedAttributes = @(
    'viewBox', 'width', 'height', 'role', 'aria-labelledby', 'color', 'id',
    'fill', 'stroke', 'stroke-width', 'stroke-linecap', 'stroke-linejoin',
    'd', 'x', 'y', 'rx', 'ry', 'cx', 'cy', 'r'
)
$iconNames = @(
    'app-mark', 'back', 'cancel-timer', 'close', 'compact', 'dislike',
    'error', 'exit-fullscreen', 'forward', 'fullscreen', 'hide', 'home',
    'like', 'minimize', 'next', 'overflow', 'pause', 'pin', 'play-pause',
    'play', 'previous', 'quit-timer', 'quit', 'repeat-one', 'repeat',
    'restore-section', 'restore-window', 'retry', 'settings', 'show',
    'shuffle', 'status', 'tray', 'volume-muted', 'volume', 'zoom-in',
    'zoom-out', 'zoom-reset'
)
# 20-DIP toolbar at 100/125/150/200%; 16-DIP taskbar at 100/125/150/200%;
# 32-DIP tray at 100/125/150/200%.
$rasterSizes = @(16, 20, 24, 25, 30, 32, 40, 48, 64)

function Resolve-RepoPath([string] $path, [string] $description) {
    $candidate = if ([IO.Path]::IsPathRooted($path)) { $path } else { Join-Path $root $path }
    $full = [IO.Path]::GetFullPath($candidate)
    $prefix = $root.TrimEnd([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar
    if (-not $full.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase) -and
        -not $full.Equals($root, [StringComparison]::OrdinalIgnoreCase)) {
        Fail "$description must remain under the repository root: $path"
    }
    return $full
}

function Fail([string] $message) {
    throw "Native icon rasterization refused: $message"
}

function Resolve-ExistingFile([string] $path, [string] $description) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        Fail "$description not found: $path"
    }
    $item = Get-Item -LiteralPath $path
    if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
        Fail "$description must not be a symlink or reparse point: $path"
    }
    return $item.FullName
}

function Read-Sha256Sidecar([string] $path) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        Fail "renderer checksum sidecar is required: $path (record the approved $rendererVersion release SHA-256 before running)"
    }
    $text = (Get-Content -LiteralPath $path -Raw).Trim()
    if ($text -notmatch '^(?i:[0-9a-f]{64})$') {
        Fail "renderer checksum sidecar must contain exactly one 64-hex SHA-256 value: $path"
    }
    return $text.ToLowerInvariant()
}

function Assert-SafeSvg([string] $path) {
    $item = Get-Item -LiteralPath $path
    if ($item.Length -gt $maxSvgBytes) {
        Fail "SVG exceeds the $maxSvgBytes byte bound: $path"
    }

    $settings = [System.Xml.XmlReaderSettings]::new()
    $settings.DtdProcessing = [System.Xml.DtdProcessing]::Prohibit
    $settings.XmlResolver = $null
    $settings.MaxCharactersInDocument = 64KB
    $settings.MaxCharactersFromEntities = 0
    $reader = $null
    $xmlNamespace = 'http://www.w3.org/2000/xmlns/'
    try {
        $reader = [System.Xml.XmlReader]::Create($path, $settings)
        $seenRoot = $false
        while ($reader.Read()) {
            if ($reader.NodeType -eq [System.Xml.XmlNodeType]::DocumentType) {
                Fail "DTD is not allowed: $path"
            }
            if ($reader.NodeType -eq [System.Xml.XmlNodeType]::ProcessingInstruction) {
                Fail "processing instructions are not allowed: $path"
            }
            if ($reader.NodeType -ne [System.Xml.XmlNodeType]::Element) {
                continue
            }

            $localName = $reader.LocalName
            if ($reader.NamespaceURI -ne $svgNamespace -or $allowedElements -notcontains $localName) {
                Fail "element <$localName> is outside the static SVG allowlist: $path"
            }
            if (-not $seenRoot) {
                if ($localName -ne 'svg') {
                    Fail "root element must be <svg>: $path"
                }
                $seenRoot = $true
                if ($reader.GetAttribute('viewBox') -ne '0 0 24 24' -or
                    $reader.GetAttribute('width') -ne '24' -or
                    $reader.GetAttribute('height') -ne '24') {
                    Fail "root viewBox/width/height is not the expected 24-unit geometry: $path"
                }
            }
            elseif ($localName -eq 'svg') {
                Fail "nested <svg> elements are not allowed: $path"
            }

            $elementDepth = $reader.Depth
            if ($reader.HasAttributes) {
                while ($reader.MoveToNextAttribute()) {
                    if ($reader.NamespaceURI -eq $xmlNamespace) {
                        if ($reader.Name -ne 'xmlns' -or $reader.Value -ne $svgNamespace -or $elementDepth -ne 0) {
                            Fail "only the supplied default SVG namespace declaration is allowed: $path"
                        }
                        continue
                    }
                    if ($reader.NamespaceURI.Length -ne 0 -or $allowedAttributes -notcontains $reader.LocalName) {
                        Fail "attribute '$($reader.Name)' is outside the static SVG allowlist: $path"
                    }
                    if ($reader.Value -match '(?i:url\s*\(|javascript:|data:|file:)') {
                        Fail "external or scripted SVG values are not allowed: $path"
                    }
                    switch ($reader.LocalName) {
                        'viewBox' { if ($localName -ne 'svg' -or $reader.Value -ne '0 0 24 24') { Fail "viewBox must remain 0 0 24 24: $path" } }
                        'role' { if ($localName -ne 'svg' -or $reader.Value -ne 'img') { Fail "role must remain img on the root svg: $path" } }
                        'fill' { if ($reader.Value -notmatch '^(none|currentColor|#[0-9a-f]{6}([0-9a-f]{2})?)$') { Fail "unsupported fill value: $path" } }
                        'stroke' { if ($reader.Value -notmatch '^(none|currentColor|#[0-9a-f]{6}([0-9a-f]{2})?)$') { Fail "unsupported stroke value: $path" } }
                        'color' { if ($reader.Value -notmatch '^#[0-9a-f]{6}([0-9a-f]{2})?$') { Fail "unsupported color value: $path" } }
                        'stroke-width' { if ($reader.Value -ne '2') { Fail "stroke width must remain 2: $path" } }
                        'stroke-linecap' { if ($reader.Value -ne 'round') { Fail "stroke linecap must remain round: $path" } }
                        'stroke-linejoin' { if ($reader.Value -ne 'round') { Fail "stroke linejoin must remain round: $path" } }
                        'aria-labelledby' { if ($localName -ne 'svg' -or $reader.Value -ne 'title') { Fail "aria-labelledby must target the supplied title: $path" } }
                        'id' { if ($localName -ne 'title' -or $reader.Value -ne 'title') { Fail "only the supplied title id is allowed: $path" } }
                    }
                }
                $reader.MoveToElement() | Out-Null
            }
        }
        if (-not $seenRoot) {
            Fail "SVG has no root element: $path"
        }
    }
    catch [System.Xml.XmlException] {
        Fail "invalid XML: $path ($($_.Exception.Message))"
    }
    finally {
        if ($null -ne $reader) { $reader.Dispose() }
    }
}

function Read-PngDimensions([string] $path) {
    $stream = [System.IO.File]::OpenRead($path)
    try {
        $bytes = [byte[]]::new(24)
        $read = $stream.Read($bytes, 0, $bytes.Length)
        if ($read -ne $bytes.Length) {
            Fail "renderer emitted a truncated PNG: $path"
        }
        $signature = [byte[]](137, 80, 78, 71, 13, 10, 26, 10)
        for ($index = 0; $index -lt $signature.Length; $index++) {
            if ($bytes[$index] -ne $signature[$index]) {
                Fail "renderer output is not a PNG: $path"
            }
        }
        if ([Text.Encoding]::ASCII.GetString($bytes, 12, 4) -ne 'IHDR') {
            Fail "renderer output has no PNG IHDR: $path"
        }
        $width = ($bytes[16] -shl 24) -bor ($bytes[17] -shl 16) -bor ($bytes[18] -shl 8) -bor $bytes[19]
        $height = ($bytes[20] -shl 24) -bor ($bytes[21] -shl 16) -bor ($bytes[22] -shl 8) -bor $bytes[23]
        return @([int]$width, [int]$height)
    }
    finally {
        $stream.Dispose()
    }
}

$RendererPath = Resolve-RepoPath $RendererPath 'renderer path'
$InputRoot = Resolve-RepoPath $InputRoot 'SVG input path'
$OutputRoot = Resolve-RepoPath $OutputRoot 'raster output path'
$localTemp = Join-Path $root '.cache\tmp'
[IO.Directory]::CreateDirectory($localTemp) | Out-Null
$previousTemp = $env:TEMP
$previousTmp = $env:TMP
try {
    $env:TEMP = $localTemp
    $env:TMP = $localTemp
$renderer = Resolve-ExistingFile $RendererPath 'resvg renderer'
$rendererHashSidecar = "$renderer.sha256"
$input = if (Test-Path -LiteralPath $InputRoot -PathType Container) {
    $inputItem = Get-Item -LiteralPath $InputRoot
    if (($inputItem.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
        Fail "mask input directory must not be a symlink or reparse point: $InputRoot"
    }
    (Resolve-Path -LiteralPath $InputRoot).Path
} else {
    Fail "mask input directory not found: $InputRoot"
}
$checksum = Read-Sha256Sidecar $rendererHashSidecar
$actualChecksum = (Get-FileHash -LiteralPath $renderer -Algorithm SHA256).Hash.ToLowerInvariant()
if ($actualChecksum -ne $checksum) {
    Fail "renderer SHA-256 does not match $rendererHashSidecar"
}
$versionText = (& $renderer '--version' 2>&1 | Out-String).Trim()
if ($LASTEXITCODE -ne 0 -or $versionText -notmatch "(?<![0-9.])$([Regex]::Escape($rendererVersion))(?![0-9.])") {
    Fail "renderer must report resvg $rendererVersion; got '$versionText'"
}

$files = @(Get-ChildItem -LiteralPath $input -File -Filter '*.svg')
$expectedFiles = @($iconNames | ForEach-Object { '{0}.svg' -f $_ })
$actualFiles = @($files.Name | Sort-Object)
$expectedSorted = @($expectedFiles | Sort-Object)
if ($actualFiles.Count -ne $expectedSorted.Count -or (Compare-Object $actualFiles $expectedSorted)) {
    Fail 'mask directory must contain exactly the 38 active SVG filenames (historical notification masks live outside this input)'
}
foreach ($file in $files) {
    if (($file.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
        Fail "SVG input must not be a symlink or reparse point: $($file.FullName)"
    }
    Assert-SafeSvg $file.FullName
}

$destination = [System.IO.Path]::GetFullPath($OutputRoot)
$destinationItem = if (Test-Path -LiteralPath $destination) { Get-Item -LiteralPath $destination } else { $null }
if ($null -ne $destinationItem) {
    if (-not $destinationItem.PSIsContainer) {
        Fail "raster output path is not a directory: $destination"
    }
    if (($destinationItem.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
        Fail "raster output directory must not be a symlink or reparse point: $destination"
    }
    $priorManifestPath = Join-Path $destination 'manifest.json'
    if (-not (Test-Path -LiteralPath $priorManifestPath -PathType Leaf)) {
        Fail 'existing output is not a generated native-icon directory'
    }
    $priorManifest = Get-Content -LiteralPath $priorManifestPath -Raw | ConvertFrom-Json
    if ($priorManifest.schema -ne 1 -or $priorManifest.source -ne 'assets/native-icons/states/mask' -or
        $priorManifest.renderer.name -ne 'resvg') {
        Fail 'existing output manifest does not identify generated native icons'
    }
}
$destinationParent = Split-Path -Parent $destination
[IO.Directory]::CreateDirectory($destinationParent) | Out-Null
$staging = Join-Path (Join-Path $root '.cache\tmp') "native-icons-$([Guid]::NewGuid().ToString('N'))"
[IO.Directory]::CreateDirectory($staging) | Out-Null
$committed = $false
$generatedAssets = [Collections.Generic.List[object]]::new()
try {
    foreach ($size in $rasterSizes) {
        $sizeDirectory = Join-Path $staging $size
        [IO.Directory]::CreateDirectory($sizeDirectory) | Out-Null
        foreach ($name in $iconNames) {
            $source = Join-Path $input "$name.svg"
            $target = Join-Path $sizeDirectory "$name.png"
            & $renderer '--skip-system-fonts' '--width' $size '--height' $size $source $target
            if ($LASTEXITCODE -ne 0) {
                Fail "resvg failed for $name at ${size}px"
            }
            if (-not (Test-Path -LiteralPath $target -PathType Leaf)) {
                Fail "resvg did not create $target"
            }
            $dimensions = Read-PngDimensions $target
            if ($dimensions[0] -ne $size -or $dimensions[1] -ne $size) {
                Fail "resvg emitted $($dimensions[0])x$($dimensions[1]) for requested ${size}x${size}: $target"
            }
            $generatedAssets.Add([ordered]@{
                path = "$size/$name.png"
                logicalName = "OAuthProbe.NativeIcons.$size.$name.png"
                width = $size
                height = $size
                sha256 = (Get-FileHash -LiteralPath $target -Algorithm SHA256).Hash.ToLowerInvariant()
            })
        }
    }
    $manifestPath = Join-Path $staging 'manifest.json'
    $manifest = [ordered]@{
        schema = 1
        source = 'assets/native-icons/states/mask'
        renderer = [ordered]@{
            name = 'resvg'
            version = $rendererVersion
            target = 'x86_64-pc-windows-msvc'
            executableSha256 = $actualChecksum
            license = $rendererLicense
        }
        sizes = $rasterSizes
        names = $iconNames
        assets = $generatedAssets
    }
    [IO.File]::WriteAllText($manifestPath,
        ($manifest | ConvertTo-Json -Depth 6) + [Environment]::NewLine,
        [Text.UTF8Encoding]::new($false))

    $old = "$destination.old-$([Guid]::NewGuid().ToString('N'))"
    if (Test-Path -LiteralPath $destination) {
        Move-Item -LiteralPath $destination -Destination $old
    }
    try {
        Move-Item -LiteralPath $staging -Destination $destination
        $committed = $true
    }
    catch {
        if (Test-Path -LiteralPath $old) { Move-Item -LiteralPath $old -Destination $destination }
        throw
    }
    if (Test-Path -LiteralPath $old) { Remove-Item -LiteralPath $old -Recurse -Force }
    Write-Host "Generated $($iconNames.Count * $rasterSizes.Count) committed PNG masks under $destination"
    Write-Host "Renderer: resvg $rendererVersion ($rendererLicense); SHA-256 $actualChecksum"
}
finally {
    if (-not $committed -and (Test-Path -LiteralPath $staging)) {
        Remove-Item -LiteralPath $staging -Recurse -Force
    }
}
}
finally {
    $env:TEMP = $previousTemp
    $env:TMP = $previousTmp
}
